nSimulationsPerTree:
  - 1
nTrialsPerPoint: 1000
dim: 3
linear: false
spacecraftMass: 1
spacecraftMoment: 4
sigmaW:
  - 0.2
  - 0.2
  - 0.01
sigmaV: 0.4
discretization: 0.125
dt: 1
nExperimentSteps: 15
saveTrajectory: true
providedFailure: null
maxNumActions: 20
rngKeysOffset: 0
actionRNGSeed: 0
diagnosisThreshold: 1.9
nMaxComponentFailures: 3
initialState:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
solverFList:
  - cbf
  - greedy
  - scp
estimator: marginalizedFilter
physicalStateSubEstimator: ekf
reward: squareSumFailureBeliefReward
safetyMethod: safetyConstrainedReward
penalty: 0
safetyFunctionEvaluation: chebyshev
allowableFailureChance: 0.1
safetyFunction: worstCase
safetyConstraints:
  - - circularObstacleConstraint
    - - 10
      - - 0
        - -20
  - - linearSafeZoneConstraint
    - - - - 1
          - 0
        - - -1
          - 0
        - - 0
          - 1
        - - 0
          - -1
      - - 25
        - 25
        - 25
        - 25
saveDirectoryPath: figure5/binaryProximityOperationsBaselines
clobber: false
nMaxPossibleFailures: 40
saveTreeFlag: false
multiprocessingFlag: 33
plottingExtent: 30
resolution: 400
hardwareEmulationFlag: false
filterDivergenceHandlingMethod: acceptDiagnosisBeforeNan
